# Exploring Global Earthquake Patterns: Where, When, and How Earthquakes Occur

This project uses a global earthquake dataset containing M4.5+ events from 1900–2026. The goal is to create a series of connected interactive visualizations that help explain where earthquakes occur, how their frequency changes over time, how strong and deep they are, and how earthquake patterns differ across regions.

The dataset contains more than 230,000 earthquake events and was collected from the U.S. Geological Survey (USGS) Earthquake Hazards Program. Each row represents one earthquake event.

The project will use Python, Pandas, Matplotlib, and Plotly for data preparation, analysis, and interactive visualization.

In [ ]:
# Mount Google drive to access files in it
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

## 1. Import Required Libraries

Before working with the earthquake dataset, the project imports the Python libraries needed for data analysis and visualization.

- **Pandas** is used to load, clean, filter, and analyze tabular data.
- **NumPy** provides numerical tools that may be useful during calculations and data preparation.
- **Matplotlib** is used for basic static visualizations.
- **Plotly Express** is used to create interactive charts and maps.
- **Plotly Graph Objects** provides more control when building advanced or customized interactive visualizations.

In [ ]:
# Import Pandas for loading, cleaning, and analyzing tabular data
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for basic static visualizations
import matplotlib.pyplot as plt

# Import Plotly Express for interactive charts and maps
import plotly.express as px

# Import Plotly Graph Objects for more customized interactive visualizations
import plotly.graph_objects as go

In [ ]:
# Load the earthquake CSV file into a Pandas DataFrame.
# "df" is a common name used for a DataFrame.

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/earthquakes.csv")

# Display the first five rows of the dataset.
# This helps confirm that the file loaded correctly.

df.head()

,usgs_id,date,year,month,lat,lon,depth_km,magnitude,mag_type,magnitude_class,location_desc,review_status,n_stations,azimuthal_gap,min_station_dist,rms
0,cent19000105190000000,1900-01-05,1900,1,-3.0,102.0,NaN,7.0,ms,Major (M7-7.9),"Southern Sumatra, Indonesia",reviewed,NaN,NaN,NaN,NaN
1,cent19000111090700000,1900-01-11,1900,1,-5.0,148.0,NaN,7.0,ms,Major (M7-7.9),Bismarck Sea,reviewed,NaN,NaN,NaN,NaN
2,cent19000120063300000,1900-01-20,1900,1,20.0,-105.0,NaN,7.3,mw,Major (M7-7.9),"Jalisco, Mexico",reviewed,NaN,NaN,NaN,NaN
3,cent19000131192200000,1900-01-31,1900,1,48.0,146.0,450.0,7.5,mj,Major (M7-7.9),Sea of Okhotsk,reviewed,NaN,NaN,NaN,NaN
4,ushis389,1900-04-30,1900,4,36.9,-121.6,NaN,4.5,ml,Light (M4.5-4.9),"Near Aromas, California",reviewed,NaN,NaN,NaN,NaN

In [ ]:
# Print the number of earthquake records in the dataset.
print("Number of rows:", df.shape[0])

# Print the number of variables/columns in the dataset.
print("Number of columns:", df.shape[1])

# Display information about every column in the dataset.
# This includes column names, non-null counts, and data types.

df.info()

Number of rows: 230805
Number of columns: 16
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230805 entries, 0 to 230804
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   usgs_id           230805 non-null  object
 1   date              230805 non-null  object
 2   year              230805 non-null  int64
 3   month             230805 non-null  int64
 4   lat               230805 non-null  float64
 5   lon               230805 non-null  float64
 6   depth_km          230068 non-null  float64
 7   magnitude         230805 non-null  float64
 8   mag_type          230804 non-null  object
 9   magnitude_class   230805 non-null  object
 10  location_desc     230805 non-null  object
 11  review_status     230805 non-null  object
 12  n_stations        79682 non-null   float64
 13  azimuthal_gap     101621 non-null  float64
 14  min_station_dist  62282 non-null   float64
 15  rms               183332 non-null  float64
dtypes: float64(8), int64(2), object(6)
memory usage: 28.2+ MB

In [ ]:
# Generate descriptive statistics for the numerical columns.
# This helps us understand the ranges and distributions in the dataset.

df.describe()

,year,month,lat,lon,depth_km,magnitude,n_stations,azimuthal_gap,min_station_dist,rms
count,230805.000000,230805.000000,230805.000000,230805.000000,230068.000000,230805.000000,79682.000000,101621.000000,62282.000000,183332.000000
mean,1996.928797,6.744928,5.634714,42.655925,71.436677,4.965707,78.332810,94.576028,4.387880,0.935497
std,21.282295,3.415986,29.466226,120.601150,117.497145,0.506384,85.252513,47.083403,5.649067,0.355263
min,1900.000000,1.000000,-83.902000,-179.999700,-3.000000,3.380000,0.000000,6.500000,0.000000,-1.000000
25%,1984.000000,4.000000,-16.071000,-71.082000,10.181500,4.600000,27.000000,59.700000,1.383000,0.760000
50%,1998.000000,7.000000,1.773000,101.654900,33.000000,4.800000,51.000000,89.200000,2.602000,0.930000
75%,2014.000000,10.000000,31.104100,142.419500,63.000000,5.200000,95.000000,123.000000,4.948000,1.100000
max,2026.000000,12.000000,87.221000,180.000000,700.900000,9.500000,934.000000,360.000000,62.558000,69.320000

In [ ]:
# Count the number of missing values in each column.
# isnull() identifies missing values.
# sum() adds them together for each column.

df.isnull().sum()

usgs_id                  0
date                     0
year                     0
month                    0
lat                      0
lon                      0
depth_km               737
magnitude                0
mag_type                 1
magnitude_class          0
location_desc            0
review_status            0
n_stations          151123
azimuthal_gap       129184
min_station_dist    168523
rms                  47473
dtype: int64

In [ ]:
# Convert the "date" column from text into Pandas datetime format.
# errors="coerce" converts invalid dates into missing values instead of causing an error.

df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Display the first few converted dates.
df["date"].head()

0   1900-01-05
1   1900-01-11
2   1900-01-20
3   1900-01-31
4   1900-04-30
Name: date, dtype: datetime64[ns]

## 8. Create a Day-of-Week Variable

The original dataset contains the earthquake date, year, and month, but it does not include a separate column showing the day of the week.

Using the converted date column, a new variable named `weekday` is created.

This variable will later support one of the project visualizations examining whether earthquake counts differ across days of the week.

Because the dataset contains only the event date rather than the complete UTC timestamp, time-of-day analysis cannot be performed from this CSV.

In [ ]:
# Extract the day name from each earthquake date.
# Examples include Monday, Tuesday, Wednesday, etc.

df["weekday"] = df["date"].dt.day_name()

# Display the original date together with the new weekday column.
df[["date", "weekday"]].head()

        date    weekday
0 1900-01-05     Friday
1 1900-01-11   Thursday
2 1900-01-20   Saturday
3 1900-01-31  Wednesday
4 1900-04-30     Monday

## 9. Examine Earthquake Magnitude Classes

The dataset already includes a categorical variable called `magnitude_class`.

This groups earthquakes into five levels:

- Light: M4.5–4.9
- Moderate: M5.0–5.9
- Strong: M6.0–6.9
- Major: M7.0–7.9
- Great: M8.0 and above.

The following cell counts how many earthquake events belong to each category.

In [ ]:
# Count the number of earthquakes in each magnitude category.
# value_counts() returns the frequency of each unique category.

df["magnitude_class"].value_counts()

magnitude_class
Light (M4.5-4.9)     145317
Moderate (M5-5.9)     72810
Strong (M6-6.9)       11242
Major (M7-7.9)         1349
Great (M8+)              87
Name: count, dtype: int64

## 10. Verify the Main Visualization Variables

Before building the visualizations, the project checks the main variables that will be used across the six views.

These include:

- date,
- year,
- month,
- weekday,
- latitude,
- longitude,
- depth,
- magnitude,
- magnitude class,
- and location description.

Displaying a sample of these fields helps verify that the necessary information is available and correctly formatted.

In [ ]:
# Select the main variables that will be used throughout the visualizations.

main_columns = [
    "date",
    "year",
    "month",
    "weekday",
    "lat",
    "lon",
    "depth_km",
    "magnitude",
    "magnitude_class",
    "location_desc"
]

# Display a sample of the selected variables.

df[main_columns].head(10)

,date,year,month,weekday,lat,lon,depth_km,magnitude,magnitude_class,location_desc
0,1900-01-05,1900,1,Friday,-3.0,102.0,NaN,7.00,Major (M7-7.9),"Southern Sumatra, Indonesia"
1,1900-01-11,1900,1,Thursday,-5.0,148.0,NaN,7.00,Major (M7-7.9),Bismarck Sea
2,1900-01-20,1900,1,Saturday,20.0,-105.0,NaN,7.30,Major (M7-7.9),"Jalisco, Mexico"
3,1900-01-31,1900,1,Wednesday,48.0,146.0,450.0,7.50,Major (M7-7.9),Sea of Okhotsk
4,1900-04-30,1900,4,Monday,36.9,-121.6,NaN,4.50,Light (M4.5-4.9),"Near Aromas, California"
5,1900-05-11,1900,5,Friday,38.7,141.1,5.0,7.00,Major (M7-7.9),"Northern Honshu, Japan"
6,1900-06-21,1900,6,Thursday,10.0,-85.5,NaN,7.20,Major (M7-7.9),Costa Rica
7,1900-07-29,1900,7,Sunday,-10.0,165.0,NaN,7.60,Major (M7-7.9),Santa Cruz Islands
8,1900-09-17,1900,9,Monday,-5.0,148.0,NaN,7.10,Major (M7-7.9),Bismarck Sea
9,1900-10-09,1900,10,Tuesday,57.4,-151.0,20.0,7.86,Major (M7-7.9),"Kodiak Island region, Alaska"

## 11. Check for Duplicate Earthquake Records

Before analyzing the dataset, it is important to confirm that the same earthquake event has not been included more than once.

Each earthquake has a unique USGS identifier stored in the `usgs_id` column. By checking for duplicate values in this field, we can determine whether the dataset contains repeated earthquake records.

Duplicate events could incorrectly increase earthquake counts and distort later visualizations.

In [ ]:
# Count duplicate earthquake IDs.
# duplicated() returns True for repeated values.
# sum() counts how many duplicate records exist.

duplicate_count = df["usgs_id"].duplicated().sum()

print("Number of duplicate earthquake IDs:", duplicate_count)

Number of duplicate earthquake IDs: 0

## 12. Investigate Missing Earthquake Depth Values

The initial data-quality check showed that some earthquake events are missing depth measurements.

Depth is important for one of the planned visualizations, so these missing values must be examined before deciding how to handle them.

Rather than replacing missing depths with an average value, the project will preserve the missing values and exclude those records only from visualizations that specifically require depth. This avoids introducing artificial depth measurements into the scientific data.

In [ ]:
# Count earthquakes that do not have a recorded depth.

missing_depth = df["depth_km"].isnull().sum()

# Calculate what percentage of the complete dataset is missing depth.

missing_depth_percent = (
    missing_depth / len(df)
) * 100

print("Earthquakes missing depth:", missing_depth)
print(
    "Percentage missing depth:",
    round(missing_depth_percent, 2),
    "%"
)

Earthquakes missing depth: 737
Percentage missing depth: 0.32 %

## 13. Verify the M4.5 Magnitude Threshold

The dataset is described as containing earthquakes with magnitude 4.5 or greater.

To verify this condition, the project checks whether any records have a magnitude below 4.5.

This validation step helps ensure that the actual data matches the documented dataset criteria.

In [ ]:
# Find any earthquake records with magnitude below 4.5.

below_threshold = df[df["magnitude"] < 4.5]

# Display the number of records found.

print(
    "Number of earthquakes below magnitude 4.5:",
    len(below_threshold)
)

# Display the unusual record, if one exists.

below_threshold[
    [
        "usgs_id",
        "date",
        "magnitude",
        "magnitude_class",
        "location_desc"
    ]
]

Number of earthquakes below magnitude 4.5: 1

,usgs_id,date,magnitude,magnitude_class,location_desc
135760,nc21364840,2004-05-17,3.38,Light (M4.5-4.9),"12 km NNE of Cayucos, California"

## 14. Examine USGS Review Status

The dataset includes a `review_status` variable indicating whether an earthquake record was manually reviewed or automatically generated.

Examining this field provides additional information about the quality and verification status of the earthquake catalog.

In [ ]:
# Count earthquake records by USGS review status.

review_counts = df["review_status"].value_counts()

review_counts

review_status
reviewed     230699
automatic       106
Name: count, dtype: int64

Convert date to month, day of month, and day of the week
## 15. Create Calendar Variables for Temporal Analysis

The dataset already includes the earthquake date, year, and numerical month.

To support more detailed temporal analysis, additional calendar variables are created from the `date` column:

- `month_name` identifies the month by name.
- `weekday` identifies the day of the week.
- `day_of_month` identifies the numerical day within the month, from 1 to 31.

These variables will allow the project to compare earthquake occurrence across months, weekdays, and days of the month.

In [ ]:
# Create the full month name from each earthquake date.
# Example: month 1 becomes "January".

df["month_name"] = df["date"].dt.month_name()

# Extract the day of the week.
# Example: Monday, Tuesday, Wednesday, etc.

df["weekday"] = df["date"].dt.day_name()

# Extract the numerical day of the month.
# Values range from 1 to 31.

df["day_of_month"] = df["date"].dt.day

# Display a sample of the calendar variables.

df[
    [
        "date",
        "year",
        "month",
        "month_name",
        "day_of_month",
        "weekday"
    ]
].head(10)

        date  year  month month_name  day_of_month    weekday
0 1900-01-05  1900      1    January             5     Friday
1 1900-01-11  1900      1    January            11   Thursday
2 1900-01-20  1900      1    January            20   Saturday
3 1900-01-31  1900      1    January            31  Wednesday
4 1900-04-30  1900      4      April            30     Monday
5 1900-05-11  1900      5        May            11     Friday
6 1900-06-21  1900      6       June            21   Thursday
7 1900-07-29  1900      7       July            29     Sunday
8 1900-09-17  1900      9  September            17     Monday
9 1900-10-09  1900     10    October             9    Tuesday

In [ ]:
# Check the range of day-of-month values.

print("Minimum day of month:", df["day_of_month"].min())
print("Maximum day of month:", df["day_of_month"].max())

# Display the weekday categories found in the dataset.

print("\nWeekdays:")
print(df["weekday"].unique())

# Display the month names found in the dataset.

print("\nMonths:")
print(df["month_name"].unique())

Minimum day of month: 1
Maximum day of month: 31

Weekdays:
['Friday' 'Thursday' 'Saturday' 'Wednesday' 'Monday' 'Sunday' 'Tuesday']

Months:
['January' 'April' 'May' 'June' 'July' 'September' 'October' 'November'
 'December' 'March' 'August' 'February']

## 16. Define the Correct Order of Magnitude Categories

Magnitude classes represent increasing earthquake strength, so they should appear in scientific order rather than alphabetical order.

The categories are therefore defined as an ordered categorical variable:

**Light → Moderate → Strong → Major → Great**

This ensures that later charts display increasing earthquake strength from left to right.

In [ ]:
# Define the scientifically meaningful order
# of the earthquake magnitude categories.

magnitude_order = [
    "Light (M4.5-4.9)",
    "Moderate (M5-5.9)",
    "Strong (M6-6.9)",
    "Major (M7-7.9)",
    "Great (M8+)"
]

# Convert magnitude_class into an ordered categorical variable.

df["magnitude_class"] = pd.Categorical(
    df["magnitude_class"],
    categories=magnitude_order,
    ordered=True
)

# Verify the categories and their order.

df["magnitude_class"].value_counts().sort_index()

magnitude_class
Light (M4.5-4.9)     145317
Moderate (M5-5.9)     72810
Strong (M6-6.9)       11242
Major (M7-7.9)         1349
Great (M8+)              87
Name: count, dtype: int64

## View 1: Earthquake Magnitude Distribution

The first visualization examines how earthquake events are distributed across magnitude classes.

Before creating the chart, the dataset is grouped by `magnitude_class`, and the number of events in each class is calculated.

This produces one count for each magnitude category from Light through Great.

In [ ]:
# Count the number of earthquake events
# belonging to each magnitude class.

mag_counts = (
    df["magnitude_class"]
    .value_counts()
    .sort_index()
    .reset_index()
)

# Rename the columns so they are easier to understand
# when used in the visualization.

mag_counts.columns = [
    "Magnitude Class",
    "Number of Earthquakes"
]

# Display the summarized table.

mag_counts

     Magnitude Class  Number of Earthquakes
0   Light (M4.5-4.9)                 145317
1  Moderate (M5-5.9)                  72810
2    Strong (M6-6.9)                  11242
3     Major (M7-7.9)                   1349
4        Great (M8+)                     87

## Interactive Magnitude-Class Visualization

# View 1 — Where Do Earthquakes Occur?

The first visualization introduces the geographic distribution of earthquakes around the world.

The main question is:

**Where have magnitude 4.5 or greater earthquakes occurred globally?**

An interactive world map displays earthquake epicenters using latitude and longitude. Users can select a year and minimum earthquake magnitude to reduce visual clutter and explore geographic patterns.

Each point represents one recorded earthquake. Hovering over a point reveals the earthquake's location, date, magnitude, and depth.

This geographic view establishes the spatial context for the rest of the scientific story.

In [ ]:
# ---------------------------------------------------------
# VIEW 1: WHERE DO EARTHQUAKES OCCUR?
# Interactive Global Earthquake Map
# ---------------------------------------------------------

import ipywidgets as widgets
from IPython.display import display, clear_output
from google.colab import output

output.enable_custom_widget_manager()


# ---------------------------------------------------------
# Create the year selector.
# ---------------------------------------------------------

map_year_slider = widgets.IntSlider(
    value=2025,
    min=1900,
    max=2026,
    step=1,
    description="Year:",
    continuous_update=False,
    layout=widgets.Layout(width="700px")
)


# ---------------------------------------------------------
# Create the minimum magnitude slider.
# ---------------------------------------------------------

magnitude_slider = widgets.FloatSlider(
    value=4.5,
    min=4.5,
    max=8.0,
    step=0.5,
    description="Min Mag:",
    continuous_update=False,
    readout_format=".1f",
    layout=widgets.Layout(width="700px")
)


# ---------------------------------------------------------
# Create a Reset button.
# ---------------------------------------------------------

map_reset_button = widgets.Button(
    description="Reset"
)


# ---------------------------------------------------------
# Create an information label.
#
# This will show:
# - how many earthquakes are currently displayed
# - what marker size means
# - a warning when 2026 is selected
# ---------------------------------------------------------

map_info = widgets.HTML()


# ---------------------------------------------------------
# Create an output area for the map.
# ---------------------------------------------------------

map_output = widgets.Output()


# ---------------------------------------------------------
# Function that updates the map.
# ---------------------------------------------------------

def update_earthquake_map(change=None):

    # Read the currently selected controls.
    selected_year = map_year_slider.value
    minimum_magnitude = magnitude_slider.value

    # Filter the dataset to the selected year
    # and minimum magnitude.
    map_df = df[
        (df["year"] == selected_year) &
        (df["magnitude"] >= minimum_magnitude)
    ].copy()

    # Count how many earthquakes match the current filters.
    event_count = len(map_df)

    # -----------------------------------------------------
    # Update the information displayed above the map.
    # -----------------------------------------------------

    if selected_year == 2026:

        map_info.value = (
            f"<b>Events shown:</b> {event_count:,}"
            "<br>"
            "<b>Marker size:</b> larger circles represent stronger earthquakes."
            "<br>"
            "<span style='color:#9a6700;'>"
            "<b>Note:</b> 2026 contains data only through May 14, 2026."
            "</span>"
        )

    else:

        map_info.value = (
            f"<b>Events shown:</b> {event_count:,}"
            "<br>"
            "<b>Marker size:</b> larger circles represent stronger earthquakes."
        )


    # -----------------------------------------------------
    # Draw the updated map.
    # -----------------------------------------------------

    with map_output:

        clear_output(wait=True)

        fig = px.scatter_geo(
            map_df,

            # Geographic position.
            lat="lat",
            lon="lon",

            # Magnitude controls marker size.
            size="magnitude",

            # Limit maximum marker size so the map
            # remains readable.
            size_max=12,

            # Main hover heading.
            hover_name="location_desc",

            # Additional information shown on hover.
            hover_data={
                "date": True,
                "magnitude": ":.1f",
                "depth_km": ":.1f",
                "lat": False,
                "lon": False
            },

            title=(
                f"Global Earthquakes in {selected_year} "
                f"(Magnitude ≥ {minimum_magnitude})"
            ),

            projection="natural earth"
        )


        # -------------------------------------------------
        # Improve marker visibility without making
        # overlapping events too difficult to interpret.
        # -------------------------------------------------

        fig.update_traces(
            marker=dict(
                opacity=0.55,
                line=dict(width=0.3)
            )
        )


        # -------------------------------------------------
        # Improve geographic context.
        # -------------------------------------------------

        fig.update_geos(
            showcoastlines=True,
            showcountries=True,
            showland=True
        )


        # -------------------------------------------------
        # Improve layout.
        # -------------------------------------------------

        fig.update_layout(
            height=600,
            margin=dict(
                l=10,
                r=10,
                t=70,
                b=10
            )
        )

        fig.show()


# ---------------------------------------------------------
# Update the map when the year changes.
# ---------------------------------------------------------

map_year_slider.observe(
    update_earthquake_map,
    names="value"
)


# ---------------------------------------------------------
# Update the map when minimum magnitude changes.
# ---------------------------------------------------------

magnitude_slider.observe(
    update_earthquake_map,
    names="value"
)


# ---------------------------------------------------------
# Reset function.
# ---------------------------------------------------------

def reset_map(button):

    # Return to a complete recent year.
    map_year_slider.value = 2025
    magnitude_slider.value = 4.5


map_reset_button.on_click(reset_map)


# ---------------------------------------------------------
# Display the controls and visualization.
# ---------------------------------------------------------

display(map_year_slider)
display(magnitude_slider)
display(map_reset_button)

# Display information about the current map.
display(map_info)

# Display the map.
display(map_output)


# Draw the initial map.
update_earthquake_map()

IntSlider(value=2025, continuous_update=False, description='Year:', layout=Layout(width='700px'), max=2026, mi…

FloatSlider(value=4.5, continuous_update=False, description='Min Mag:', layout=Layout(width='700px'), max=8.0,…

Button(description='Reset', style=ButtonStyle())

HTML(value='')

Output()

# View 2 — How Has Earthquake Activity Changed Over Time?

This visualization examines how the number of recorded earthquakes changes across the historical dataset.

A line chart is used because time is ordered and the goal is to show patterns and changes across years.

Users can adjust the minimum magnitude to compare how the historical pattern changes when only stronger earthquakes are included.

Because earthquake monitoring technology and global reporting improved over time, increases in recorded earthquake counts should not automatically be interpreted as evidence that earthquakes have become physically more frequent.

In [ ]:
# ---------------------------------------------------------
# VIEW 2: HOW HAS EARTHQUAKE ACTIVITY CHANGED OVER TIME?
# Interactive Yearly Earthquake Timeline
# ---------------------------------------------------------

import numpy as np
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output


# ---------------------------------------------------------
# Create a minimum magnitude slider.
# ---------------------------------------------------------

timeline_mag_slider = widgets.FloatSlider(
    value=4.5,
    min=4.5,
    max=8.0,
    step=0.5,
    description="Min Mag:",
    continuous_update=False,
    readout_format=".1f",
    layout=widgets.Layout(width="700px")
)


# ---------------------------------------------------------
# Create a Reset button.
# ---------------------------------------------------------

timeline_reset_button = widgets.Button(
    description="Reset"
)


# ---------------------------------------------------------
# Create an explanatory text area.
# ---------------------------------------------------------

timeline_info = widgets.HTML()


# ---------------------------------------------------------
# Create an output area for the chart.
# ---------------------------------------------------------

timeline_output = widgets.Output()


# ---------------------------------------------------------
# Function that updates the timeline.
# ---------------------------------------------------------

def update_timeline(change=None):

    # Read the selected minimum magnitude.
    minimum_magnitude = timeline_mag_slider.value

    # -----------------------------------------------------
    # Filter the dataset.
    #
    # 2026 is excluded because it is only a partial year.
    # -----------------------------------------------------

    filtered_df = df[
        (df["magnitude"] >= minimum_magnitude) &
        (df["year"] <= 2025)
    ].copy()


    # -----------------------------------------------------
    # Count earthquake records for each year.
    # -----------------------------------------------------

    yearly_counts = (
        filtered_df
        .groupby("year")
        .size()
        .reset_index(name="Number of Earthquakes")
    )


    # -----------------------------------------------------
    # Create a complete year sequence from 1900 to 2025.
    #
    # This makes missing years explicit instead of
    # silently skipping them.
    # -----------------------------------------------------

    all_years = pd.DataFrame({
        "year": range(1900, 2026)
    })

    yearly_counts = all_years.merge(
        yearly_counts,
        on="year",
        how="left"
    )


    # -----------------------------------------------------
    # Mark known incomplete / missing coverage years.
    #
    # 2005 has no records.
    # 2006 contains only Dec 8–31.
    #
    # Setting these values to NaN tells Plotly to leave
    # a visible break in the line.
    # -----------------------------------------------------

    yearly_counts.loc[
        yearly_counts["year"].isin([2005, 2006]),
        "Number of Earthquakes"
    ] = np.nan


    # -----------------------------------------------------
    # Update explanatory text shown above the chart.
    # -----------------------------------------------------

    timeline_info.value = (
        f"<b>Selected threshold:</b> Magnitude ≥ {minimum_magnitude:.1f}"
        "<br>"
        "<b>How to read this view:</b> "
        "Each point represents the number of recorded earthquakes "
        "during one year."
        "<br>"
        "<b>Important limitation:</b> Earlier historical counts may be "
        "affected by changes in earthquake monitoring and reporting."
        "<br>"
        "<b>Data coverage note:</b> "
        "2005 has no records in this dataset, and 2006 contains only "
        "partial coverage from December 8–31. "
        "The line is intentionally broken across this period."
        "<br>"
        "<b>Displayed period:</b> 1900–2025. "
        "The partial 2026 data are excluded from the yearly trend."
    )


    # -----------------------------------------------------
    # Draw the updated chart.
    # -----------------------------------------------------

    with timeline_output:

        clear_output(wait=True)

        fig = px.line(
            yearly_counts,
            x="year",
            y="Number of Earthquakes",
            markers=True,

            title=(
                f"Recorded Earthquakes by Year "
                f"(Magnitude ≥ {minimum_magnitude:.1f})"
            ),

            hover_data={
                "year": True,
                "Number of Earthquakes": ":,"
            }
        )


        # -------------------------------------------------
        # Keep the line broken across missing values.
        # -------------------------------------------------

        fig.update_traces(
            connectgaps=False,
            marker=dict(size=5),
            line=dict(width=2)
        )


        # -------------------------------------------------
        # Add an annotation identifying the coverage gap.
        # -------------------------------------------------

        fig.add_annotation(
            x=2005.5,

            # Place annotation near the bottom of the chart.
            y=0,

            text=(
                "Data coverage gap<br>"
                "2005: no records<br>"
                "2006: partial year"
            ),

            showarrow=True,

            # Point the arrow toward the missing section.
            ax=0,
            ay=-80,

            align="center"
        )


        # -------------------------------------------------
        # Improve chart readability.
        # -------------------------------------------------

        fig.update_layout(
            xaxis_title="Year",
            yaxis_title="Number of Recorded Earthquakes",
            template="plotly_white",
            hovermode="x unified",
            height=550,
            margin=dict(
                l=70,
                r=30,
                t=90,
                b=70
            )
        )


        # -------------------------------------------------
        # Keep the x-axis focused on the actual data range.
        # -------------------------------------------------

        fig.update_xaxes(
            dtick=10,
            range=[1900, 2025]
        )


        # -------------------------------------------------
        # Display the chart.
        # -------------------------------------------------

        fig.show()


# ---------------------------------------------------------
# Update the chart when the magnitude threshold changes.
# ---------------------------------------------------------

timeline_mag_slider.observe(
    update_timeline,
    names="value"
)


# ---------------------------------------------------------
# Reset function.
# ---------------------------------------------------------

def reset_timeline(button):

    timeline_mag_slider.value = 4.5


timeline_reset_button.on_click(reset_timeline)


# ---------------------------------------------------------
# Display the controls and visualization.
# ---------------------------------------------------------

display(timeline_mag_slider)
display(timeline_reset_button)
display(timeline_info)
display(timeline_output)


# ---------------------------------------------------------
# Draw the initial chart.
# ---------------------------------------------------------

update_timeline()

FloatSlider(value=4.5, continuous_update=False, description='Min Mag:', layout=Layout(width='700px'), max=8.0,…

Button(description='Reset', style=ButtonStyle())

HTML(value='')

Output()